# main text of home
title: Ricardo "Color Crow" Rodrigues
bio: Boyfriend and friend to great people. Game Developer, Ph.D., AI Researcher

# twitter summary info
description: Boyfriend and friend to great people. Game Developer, Ph.D., AI Researcher

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/uploads/profile.jpg

# your site color theme, true for dark theme, 
# false to light theme, auto to switch with system.
dark-theme: auto
accent-color: "#308941"
accent-color-dark: "#41A700"
background: "linear-gradient(315deg, white 0%, white 60%, #D9FFE0 100%)"
background-dark: "linear-gradient(315deg, black 0%, black 60%, #143300 100%)"

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: false
resume-url: assets/uploads/cv-ricardo-rodrigues.pdf

url: https://colorcrow.me
# your url: https://USERNAME.github.io

permalink: /:title/

# To enable google analytics, supply your token below
analytics-google: 'G-5ZB1CTDL14'

# if you don't want comments in your posts, leave categories empty
disqus:
   shortname: ricardoeprodrigues # enter this from your disqus account
   categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
twitter: Quenestil
linkedin: ricardoeprodrigues
orcid: 0000-0003-0158-1460
github: RicardoEPRodrigues
itchio: colorcrow
twitch: ricardoeprodrigues
email: ricardo@colorcrow.me

authors:
  ricardorodrigues:
    name: Ricardo Rodrigues
    bio: Boyfriend and Friend to great people, Game Developer, Ph.D. student, AI Researcher
    external-image: false
    picture: assets/uploads/profile.jpg
    twitter: Quenestil

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you do/don't need pagination, toggle 'enabled' between true/false below
pagination:
  # Disable if you want to use github pages.
  enabled: false
  sort_reverse: true # display recent posts first
  title: ":title" # Changing this will mess up the header display logic
  per_page: 5
  permalink: "/:num/" # pagination link that will be appended

collections:
  projects:
    output: true

feed:
  collections:
    - projects

# if you don't need projects, comment the *projects* configs below
show_projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

# add default values to specific pages or layouts
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      layout: "post"
    values:
      # setting all post to not hidden by default,
      # can be overridden in the front matter for a specific post
      hidden: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-paginate-v2
  - jekyll-target-blank

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "vendor",
  ]
